name: Robot Framework Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework robotframework-requests python-dotenv
    
    - name: Set environment variables
      run: |
        echo "ENV_BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV
        echo "ENV_USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
        echo "ENV_PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV

    
    - name: Run Robot Framework tests
      run: |
        robot --outputdir . TEST/
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: robot-test-results
        path: |
          log.html
          output.xml
          report.html 